//! Built-in themes shipped with the binary.
//!
//! This module is auto-generated by build.rs at compile time.
//! It discovers themes in the themes/ directory and embeds them:
//!
//! - **Classic themes**: Embed entire theme directory
//! - **Vite themes** (with package.json + vite.config.*): Embed dist/ subdirectory
//!
//! Hidden files and .gitignore'd files are automatically excluded.

include!(concat!(env!("OUT_DIR"), "/builtin_themes.rs"));
